usePermissions: false
listen:
    respawn: true
worlds:
    normalWorld: world
    netherWorld: world_nether
scale:
    normal: 8
    nether: 1
forceLoadRadius: 0
forcePeacefulNether: false
forceNetherNight: false
debug: 0
